[package]
  cjc-version = "1.0.0"
  version = "0.7.7"
  name = "jinguissl"
  output-type = "static"
  src-dir = "src"
  compile-option = "-Woff unused"
  license = "Apache-2.0"
  description = "Cangjie application facade for cryptography, X.509, TLS, SSH, and QUIC contracts"
  include = ["src"]

[dependencies]
  jinguissl_core = { git = "https://gitcode.com/CjKu/JinguiCore.git" }
